### ISSUE TITLE
MVVM setup for blogs

### ISSUE THREAD

**Issue by ankurxshukla** [dsc-nsut/DSC-NSUT-App#1]
Tasks:
1. Create a model data class for blogs.
2. Create a blog repository class for fetching and sending data to Firebase. Use pagination for fetching blogs. The content of a blog will be in HTML, so that styling can be applied.
3. Create a ViewModel class which will act data source for the UI.

_Note: Work only on the data source in this issue. Extracting data into UI will be handled in a different issue._

**Comment by Artshouldterrify** [comment]
I'd like to take this up.
