### ISSUE TITLE
Layout for blogs list fragment

### ISSUE THREAD

**Issue by ankurxshukla** [dsc-nsut/DSC-NSUT-App#10]
Tasks:
1. Create a layout for blog row (check figma for design)
2. Use the blog view model to fetch and update blogs list

**Comment by thisDhruv** [comment]
I want to work on this.

**Comment by swstii** [comment]
> I want to work on this.

i am working with him.

**Comment by SwastiDDF** [comment]
> > I want to work on this.
> 
> i am working with him.

also vishad is working too

**Comment by vishad-tyagi** [comment]
i m also working with them
