### ISSUE TITLE
MVVM setup for events

### ISSUE THREAD

**Issue by ankurxshukla** [dsc-nsut/DSC-NSUT-App#2]
Tasks:
1. Create a model data class for events.
2. Create an event repository class for fetching and sending data to Firebase. Use pagination for fetching events.
3. Create a ViewModel class which will act data source for the UI.

_Note: Work only on the data source in this issue. Extracting data into UI will be handled in a different issue._

**Comment by Harshita28-01** [comment]
I would like to work on this.
