### ISSUE TITLE
MVVM setup for society members

### ISSUE THREAD

**Issue by ankurxshukla** [dsc-nsut/DSC-NSUT-App#3]
Tasks:
1. Create a model data class for members.
2. Create a members repository class for fetching and sending data to Firebase. Fetch all the data at once. For members' avatars, Firebase Storage will be used to store image files and the file names will be stored in Firestore docs.
3. Create a ViewModel class which will act data source for the UI.

_Note: Work only on the data source in this issue. Extracting data into UI will be handled in a different issue._

**Comment by visheshnaithani** [comment]
Me and Pushp are taking up this one
